using UnityEngine;
using UnityEngine.SceneManagement;

public class PlayerCollision : MonoBehaviour
{
    void OnTriggerEnter(Collider other)
    {
        if (other.CompareTag("Car"))
        {
            Debug.Log("ðŸš— Te atropellÃ³ un coche");
            FindObjectOfType<GameOverManager>().ShowGameOver();
        }
        else if (other.CompareTag("Trunk"))
        {
            Debug.Log("ðŸªµ Te llevÃ³ un buen tronco");
            FindObjectOfType<GameOverManager>().ShowGameOver();
        }
        else if (other.CompareTag("Decoration"))
        {
            Debug.Log("Es decoraciÃ³n, sigue jugando");
        }
    }
}
